version: '3.1'

services:
  blackjack21-api:
    image: blackjack21-api:latest
    build:
      context: .
    container_name: blackjack21-api
    depends_on:
      - blackjack21-database
    ports:
      - '8080:8080'
    environment:
      DB_HOST: postgres:5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: blackjack21

  blackjack21-database:
    container_name: blackjack21-database
    hostname: postgres
    image: postgres:16.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blackjack21
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5