spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/blackjack21?stringtype=unspecified&reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true