spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/blackjack21?stringtype=unspecified&reWriteBatchedInserts=true
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

